FROM ubuntu:12.04
MAINTAINER How are you? "docker@howareyou.com"

RUN apt-get install python
RUN apt-get install python-software-properties
RUN apt-get install make
RUN apt-get install g++
RUN add-apt-repository "deb http://archive.ubuntu.com/ubuntu precise universe" && apt-get update -y
RUN add-apt-repository "ppa:chris-lea/node.js" && apt-get update -y && apt-get install -y nodejs
