FROM howareyou/precise
MAINTAINER How are you? "docker@howareyou.com"

ENV REDIS_VERSION 2.6.16

RUN apt-get install build-essential
RUN wget -O - http://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz | tar -C /usr/local/src -zxv
RUN cd /usr/local/src/redis-$REDIS_VERSION && make && make install
RUN sysctl vm.overcommit_memory=1

CMD redis-server
