FROM ubuntu:12.04
MAINTAINER How are you? "docker@howareyou.com"

RUN apt-get install -y python-software-properties
RUN add-apt-repository -y ppa:nginx/stable && apt-get update -y
RUN apt-get install -y nginx

CMD nginx && /bin/bash

EXPOSE 80
EXPOSE 443
