FROM howareyou/precise
MAINTAINER How are you? "docker@howareyou.com"

RUN apt-get install python-software-properties
RUN add-apt-repository -y ppa:nginx/stable && apt-get update

RUN apt-get install nginx
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

CMD nginx

EXPOSE 80
EXPOSE 443
