FROM ubuntu:12.04
MAINTAINER How are you? "docker@howareyou.com"

RUN apt-get install -y python-software-properties
RUN add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu precise universe" && apt-get update -y
RUN apt-get install -q -y openjdk-7-jre-headless
ADD http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war /usr/local/bin/jenkins.war

CMD java -jar /usr/local/bin/jenkins.war

EXPOSE 8080
